GET https://localhost:5001/todos

##

POST https://localhost:5001/todo
Content-Type: application/json

{"Title":"Finish this post"}

##

:todo-id = 5c34680e-1d96-4058-83bc-fafb7524276d

GET https://localhost:5001/todo/:todo-id