GET https://localhost:5001/todos

##

POST https://localhost:5001/todo
Content-Type: application/json

{"Title":"Finish this post"}

##

:todo-id = 898d0e78-a07f-4198-915e-94e8486ea753

GET https://localhost:5001/todo/:todo-id